name: Website Test and Publish Report

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run TestNG Suite
        run: mvn clean test
        continue-on-error: true

      - name: Verify Allure Results
        if: always()
        run: |
          echo "Checking Allure Results..."
          ls -la target/allure-results || true

      # Download existing gh-pages branch
      - name: Get Allure History
        if: always()
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      # Generate report with history
      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          gh_pages: gh-pages
          keep_reports: 20

      # Remove nested git metadata
      - name: Remove Nested Git Folder
        if: always()
        run: |
          rm -rf allure-history/.git || true

      - name: Publish Report To GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history