name: Website Test and Publish Report

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

  workflow_dispatch:

permissions:
  contents: write

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run TestNG Suite
        run: mvn clean test

      - name: Debug Allure Files
        if: always()
        run: |
          echo "Finding allure directories..."
          find . -type d | grep allure || true

          echo "Finding allure files..."
          find . -type f | grep allure || true

      - name: Verify Allure Results
        if: always()
        run: |
          echo "Contents of target/allure-results"
          ls -la target/allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Publish Report To GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history